// This file is @generated by prost-build.
/// A store file as its own header and signature block describe it.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<super::Id>,
    /// Holds ids first_id .. first_id + num_entries - 1.
    #[prost(message, optional, tag = "2")]
    pub first_id: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "3")]
    pub num_entries: u64,
    #[prost(uint64, tag = "4")]
    pub file_bytes: u64,
    /// WAL bytes before compression; 0 when not known.
    #[prost(uint64, tag = "5")]
    pub raw_bytes: u64,
    #[prost(enumeration = "Compression", tag = "6")]
    pub compression: i32,
    #[prost(enumeration = "Encryption", tag = "7")]
    pub encryption: i32,
    /// The same 64 bytes as in the file, so an object can be matched against
    /// this record without downloading it.
    #[prost(bytes = "bytes", tag = "8")]
    pub content_signature: ::prost::bytes::Bytes,
}
/// ET_FILE_IN_CLOUD
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InCloud {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub upload_ms: u64,
    /// Every file of the queue up to this id is in the cloud, so local copies
    /// up to it may be deleted.
    #[prost(message, optional, tag = "3")]
    pub in_cloud_through: ::core::option::Option<super::Id>,
}
/// ET_CLOUD_UPLOAD_FAILED. Attempts 1, 2, 4, 8 and so on are reported.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadFailed {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<super::Id>,
    #[prost(enumeration = "UploadFailure", tag = "2")]
    pub reason: i32,
    #[prost(uint32, tag = "3")]
    pub http_status: u32,
    #[prost(uint64, tag = "4")]
    pub local_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub remote_bytes: u64,
    #[prost(string, tag = "6")]
    pub error: ::prost::alloc::string::String,
}
/// ET_DISK_FILE_DELETED
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskFileDeleted {
    #[prost(enumeration = "FileKind", tag = "1")]
    pub kind: i32,
    #[prost(message, optional, tag = "2")]
    pub file_id: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "3")]
    pub bytes: u64,
    /// The file was in the cloud when it was deleted locally.
    #[prost(bool, tag = "4")]
    pub in_cloud: bool,
    /// The queue's bytes on disk after the deletion.
    #[prost(uint64, tag = "5")]
    pub queue_bytes: u64,
}
/// ET_DISK_CLEANUP_BLOCKED. Reported once per reason until the queue is back
/// under the limit or the reason changes.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskCleanupBlocked {
    #[prost(enumeration = "CleanupBlock", tag = "1")]
    pub reason: i32,
    /// The file cleanup stopped at.
    #[prost(message, optional, tag = "2")]
    pub held_at: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "3")]
    pub queue_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub limit_bytes: u64,
}
/// ET_QUEUE_WAITING_FOR_MEMORY: when the wait starts, every 30 seconds while it
/// lasts, and once with resumed when it ends.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryWait {
    #[prost(uint64, tag = "1")]
    pub waits: u64,
    #[prost(uint64, tag = "2")]
    pub waiting_ms: u64,
    #[prost(bool, tag = "3")]
    pub resumed: bool,
}
/// ET_QUEUE_OPENED, ET_QUEUE_CLOSED
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueueState {
    #[prost(message, optional, tag = "1")]
    pub last_id: ::core::option::Option<super::Id>,
    #[prost(bool, tag = "2")]
    pub readonly: bool,
    #[prost(bool, tag = "3")]
    pub wal: bool,
    #[prost(bool, tag = "4")]
    pub store: bool,
    #[prost(bool, tag = "5")]
    pub cloud: bool,
}
/// The fields after queue belong to the event types named on each; the rest
/// are left unset.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag = "1")]
    pub stamp: ::core::option::Option<super::Stamp>,
    #[prost(enumeration = "EventType", tag = "2")]
    pub r#type: i32,
    /// Emission never waits, so events dropped since the previous record are
    /// counted instead.
    #[prost(uint64, tag = "3")]
    pub dropped_before: u64,
    #[prost(string, tag = "4")]
    pub queue: ::prost::alloc::string::String,
    /// ET_FILE_ON_DISK, ET_FILE_IN_CLOUD
    #[prost(message, optional, tag = "10")]
    pub file: ::core::option::Option<File>,
    #[prost(message, optional, tag = "11")]
    pub in_cloud: ::core::option::Option<InCloud>,
    #[prost(message, optional, tag = "12")]
    pub upload_failed: ::core::option::Option<UploadFailed>,
    #[prost(message, optional, tag = "13")]
    pub disk_file_deleted: ::core::option::Option<DiskFileDeleted>,
    #[prost(message, optional, tag = "14")]
    pub disk_cleanup_blocked: ::core::option::Option<DiskCleanupBlocked>,
    #[prost(message, optional, tag = "15")]
    pub memory_wait: ::core::option::Option<MemoryWait>,
    #[prost(message, optional, tag = "16")]
    pub queue_state: ::core::option::Option<QueueState>,
}
/// What NormFS did with a queue's files, one Event per record of
/// `<instance>/normfs/system`. Only NormFS writes there.
///
/// Where a store file is reported depends on the queue's Persist:
///    store only             FILE_ON_DISK
///    store + cloud          FILE_ON_DISK when it is written locally, then
///                           FILE_IN_CLOUD once the offloader has uploaded it.
///                           The disk monitor deletes the local copy, as
///                           DISK_FILE_DELETED with in_cloud set, only once it is
///                           in the bucket. A file uploaded just before the
///                           process stopped can lack FILE_IN_CLOUD: the next run
///                           finds it in the bucket and does not report it.
///    cloud without store    FILE_IN_CLOUD only, uploaded straight from memory
/// A failed upload is retried and reported as CLOUD_UPLOAD_FAILED until it
/// goes through. WAL files are reported only when the disk monitor deletes them.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    /// The store file is on the local disk: written, synced and renamed into
    /// the queue's store directory. Set: file.
    EtFileOnDisk = 0,
    /// The store file is in the bucket and its size was read back, so readers
    /// can fetch it from there. Set: file, in_cloud.
    EtFileInCloud = 1,
    /// One upload attempt failed; it is retried every second. Set:
    /// upload_failed.
    EtCloudUploadFailed = 2,
    /// The disk monitor deleted a local file to keep the queue under its limit.
    /// Set: disk_file_deleted.
    EtDiskFileDeleted = 3,
    /// The queue is over its disk limit but the next file may not be deleted.
    /// Set: disk_cleanup_blocked.
    EtDiskCleanupBlocked = 4,
    /// Appenders of the queue are waiting for a memory page: files are not
    /// draining it fast enough. Set: memory_wait.
    EtQueueWaitingForMemory = 5,
    /// Set: queue_state.
    EtQueueOpened = 6,
    /// Set: queue_state (last_id).
    EtQueueClosed = 7,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EventType::EtFileOnDisk => "ET_FILE_ON_DISK",
            EventType::EtFileInCloud => "ET_FILE_IN_CLOUD",
            EventType::EtCloudUploadFailed => "ET_CLOUD_UPLOAD_FAILED",
            EventType::EtDiskFileDeleted => "ET_DISK_FILE_DELETED",
            EventType::EtDiskCleanupBlocked => "ET_DISK_CLEANUP_BLOCKED",
            EventType::EtQueueWaitingForMemory => "ET_QUEUE_WAITING_FOR_MEMORY",
            EventType::EtQueueOpened => "ET_QUEUE_OPENED",
            EventType::EtQueueClosed => "ET_QUEUE_CLOSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ET_FILE_ON_DISK" => Some(Self::EtFileOnDisk),
            "ET_FILE_IN_CLOUD" => Some(Self::EtFileInCloud),
            "ET_CLOUD_UPLOAD_FAILED" => Some(Self::EtCloudUploadFailed),
            "ET_DISK_FILE_DELETED" => Some(Self::EtDiskFileDeleted),
            "ET_DISK_CLEANUP_BLOCKED" => Some(Self::EtDiskCleanupBlocked),
            "ET_QUEUE_WAITING_FOR_MEMORY" => Some(Self::EtQueueWaitingForMemory),
            "ET_QUEUE_OPENED" => Some(Self::EtQueueOpened),
            "ET_QUEUE_CLOSED" => Some(Self::EtQueueClosed),
            _ => None,
        }
    }
}
/// Values as in the store header.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Compression {
    CNone = 0,
    CGzip = 1,
    CXz = 2,
    CZstd = 3,
}
impl Compression {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Compression::CNone => "C_NONE",
            Compression::CGzip => "C_GZIP",
            Compression::CXz => "C_XZ",
            Compression::CZstd => "C_ZSTD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "C_NONE" => Some(Self::CNone),
            "C_GZIP" => Some(Self::CGzip),
            "C_XZ" => Some(Self::CXz),
            "C_ZSTD" => Some(Self::CZstd),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Encryption {
    ENone = 0,
    EAes = 1,
}
impl Encryption {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Encryption::ENone => "E_NONE",
            Encryption::EAes => "E_AES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "E_NONE" => Some(Self::ENone),
            "E_AES" => Some(Self::EAes),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileKind {
    FkWal = 0,
    FkStore = 1,
}
impl FileKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FileKind::FkWal => "FK_WAL",
            FileKind::FkStore => "FK_STORE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FK_WAL" => Some(Self::FkWal),
            "FK_STORE" => Some(Self::FkStore),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UploadFailure {
    UfNetwork = 0,
    UfHttpStatus = 1,
    UfMissing = 2,
    UfSizeMismatch = 3,
    UfLocalRead = 4,
}
impl UploadFailure {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            UploadFailure::UfNetwork => "UF_NETWORK",
            UploadFailure::UfHttpStatus => "UF_HTTP_STATUS",
            UploadFailure::UfMissing => "UF_MISSING",
            UploadFailure::UfSizeMismatch => "UF_SIZE_MISMATCH",
            UploadFailure::UfLocalRead => "UF_LOCAL_READ",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UF_NETWORK" => Some(Self::UfNetwork),
            "UF_HTTP_STATUS" => Some(Self::UfHttpStatus),
            "UF_MISSING" => Some(Self::UfMissing),
            "UF_SIZE_MISMATCH" => Some(Self::UfSizeMismatch),
            "UF_LOCAL_READ" => Some(Self::UfLocalRead),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CleanupBlock {
    /// The next file to delete is not in the cloud yet.
    CbNotInCloud = 0,
    CbDeleteFailed = 1,
    CbNothingToFind = 2,
}
impl CleanupBlock {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CleanupBlock::CbNotInCloud => "CB_NOT_IN_CLOUD",
            CleanupBlock::CbDeleteFailed => "CB_DELETE_FAILED",
            CleanupBlock::CbNothingToFind => "CB_NOTHING_TO_FIND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CB_NOT_IN_CLOUD" => Some(Self::CbNotInCloud),
            "CB_DELETE_FAILED" => Some(Self::CbDeleteFailed),
            "CB_NOTHING_TO_FIND" => Some(Self::CbNothingToFind),
            _ => None,
        }
    }
}
