// This file is @generated by prost-build.
/// One record of the system queue, `<instance>/normfs/system`. Only NormFS
/// writes there; a client write to that path is refused.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(uint64, tag = "1")]
    pub unix_ns: u64,
    /// When this process started, so a consumer can tell lives apart even
    /// when the wall clock jumps.
    #[prost(uint64, tag = "2")]
    pub started_unix_ns: u64,
    /// Events this process dropped since the previous one it recorded.
    /// Emission never waits, so a lost event is counted instead.
    #[prost(uint64, tag = "3")]
    pub dropped_before: u64,
    #[prost(oneof = "event::Kind", tags = "10, 11, 12, 13, 14, 15, 16, 17")]
    pub kind: ::core::option::Option<event::Kind>,
}
/// Nested message and enum types in `Event`.
pub mod event {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "10")]
        FileStored(super::FileStored),
        #[prost(message, tag = "11")]
        FileLanded(super::FileLanded),
        #[prost(message, tag = "12")]
        UploadFailed(super::UploadFailed),
        #[prost(message, tag = "13")]
        FileEvicted(super::FileEvicted),
        #[prost(message, tag = "14")]
        EvictionBlocked(super::EvictionBlocked),
        #[prost(message, tag = "15")]
        PoolStalled(super::PoolStalled),
        #[prost(message, tag = "16")]
        QueueStarted(super::QueueStarted),
        #[prost(message, tag = "17")]
        QueueClosed(super::QueueClosed),
    }
}
/// A store file as its own header and signature block describe it.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    #[prost(string, tag = "1")]
    pub queue: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub file_id: ::core::option::Option<super::Id>,
    /// Holds ids first_id .. first_id + num_entries - 1.
    #[prost(message, optional, tag = "3")]
    pub first_id: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "4")]
    pub num_entries: u64,
    #[prost(uint64, tag = "5")]
    pub file_bytes: u64,
    /// WAL bytes before compression; 0 when not known.
    #[prost(uint64, tag = "6")]
    pub raw_bytes: u64,
    #[prost(enumeration = "Compression", tag = "7")]
    pub compression: i32,
    #[prost(enumeration = "Encryption", tag = "8")]
    pub encryption: i32,
    /// Ed25519 over the file body, the same 64 bytes as in the file, so an
    /// object can be matched against this record without downloading it.
    #[prost(bytes = "bytes", tag = "9")]
    pub content_signature: ::prost::bytes::Bytes,
}
/// A store file reached the local store directory.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileStored {
    #[prost(message, optional, tag = "1")]
    pub file: ::core::option::Option<File>,
}
/// A store file is in the bucket and its size was read back. Its entries can
/// be read from the cloud from now on.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileLanded {
    #[prost(message, optional, tag = "1")]
    pub file: ::core::option::Option<File>,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub duration_ms: u64,
    /// The queue has nothing left to upload up to this file: local copies up
    /// to it may be deleted.
    #[prost(message, optional, tag = "4")]
    pub landed_through: ::core::option::Option<super::Id>,
}
/// An upload attempt failed; it is retried. A queue's offloader retries every
/// second, and reports attempts 1, 2, 4, 8 and so on.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadFailed {
    #[prost(string, tag = "1")]
    pub queue: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub file_id: ::core::option::Option<super::Id>,
    #[prost(enumeration = "upload_failed::Reason", tag = "3")]
    pub reason: i32,
    #[prost(uint32, tag = "4")]
    pub http_status: u32,
    #[prost(uint64, tag = "5")]
    pub local_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub remote_bytes: u64,
    #[prost(string, tag = "7")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `UploadFailed`.
pub mod upload_failed {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Reason {
        RNetwork = 0,
        RHttpStatus = 1,
        RMissing = 2,
        RSizeMismatch = 3,
        RLocalRead = 4,
    }
    impl Reason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Reason::RNetwork => "R_NETWORK",
                Reason::RHttpStatus => "R_HTTP_STATUS",
                Reason::RMissing => "R_MISSING",
                Reason::RSizeMismatch => "R_SIZE_MISMATCH",
                Reason::RLocalRead => "R_LOCAL_READ",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "R_NETWORK" => Some(Self::RNetwork),
                "R_HTTP_STATUS" => Some(Self::RHttpStatus),
                "R_MISSING" => Some(Self::RMissing),
                "R_SIZE_MISMATCH" => Some(Self::RSizeMismatch),
                "R_LOCAL_READ" => Some(Self::RLocalRead),
                _ => None,
            }
        }
    }
}
/// The disk monitor deleted a local file to keep its queue under the limit.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEvicted {
    #[prost(string, tag = "1")]
    pub queue: ::prost::alloc::string::String,
    #[prost(enumeration = "FileKind", tag = "2")]
    pub kind: i32,
    #[prost(message, optional, tag = "3")]
    pub file_id: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "4")]
    pub file_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub queue_bytes: u64,
    #[prost(bool, tag = "6")]
    pub in_cloud: bool,
}
/// Over its limit, the queue keeps files it may not delete yet. Reported once
/// per reason until the queue is back under the limit or the reason changes.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvictionBlocked {
    #[prost(string, tag = "1")]
    pub queue: ::prost::alloc::string::String,
    #[prost(enumeration = "eviction_blocked::Reason", tag = "2")]
    pub reason: i32,
    #[prost(message, optional, tag = "3")]
    pub held_at: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "4")]
    pub queue_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub limit_bytes: u64,
}
/// Nested message and enum types in `EvictionBlocked`.
pub mod eviction_blocked {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Reason {
        RNotOffloaded = 0,
        RDeleteFailed = 1,
        RNothingFound = 2,
    }
    impl Reason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Reason::RNotOffloaded => "R_NOT_OFFLOADED",
                Reason::RDeleteFailed => "R_DELETE_FAILED",
                Reason::RNothingFound => "R_NOTHING_FOUND",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "R_NOT_OFFLOADED" => Some(Self::RNotOffloaded),
                "R_DELETE_FAILED" => Some(Self::RDeleteFailed),
                "R_NOTHING_FOUND" => Some(Self::RNothingFound),
                _ => None,
            }
        }
    }
}
/// Appenders of a queue are waiting for a page: the files are not draining it
/// fast enough. Reported when the stall starts, every 30 seconds while it
/// lasts, and once with `resumed` when it ends.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolStalled {
    #[prost(string, tag = "1")]
    pub queue: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub waits: u64,
    #[prost(uint64, tag = "3")]
    pub stalled_for_ms: u64,
    #[prost(bool, tag = "4")]
    pub resumed: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueueStarted {
    #[prost(string, tag = "1")]
    pub queue: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub readonly: bool,
    #[prost(bool, tag = "3")]
    pub wal: bool,
    #[prost(bool, tag = "4")]
    pub store: bool,
    #[prost(bool, tag = "5")]
    pub cloud: bool,
    #[prost(message, optional, tag = "6")]
    pub last_id: ::core::option::Option<super::Id>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueueClosed {
    #[prost(string, tag = "1")]
    pub queue: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub last_id: ::core::option::Option<super::Id>,
}
/// Values as in the store header.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Compression {
    CNone = 0,
    CGzip = 1,
    CXz = 2,
    CZstd = 3,
}
impl Compression {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Compression::CNone => "C_NONE",
            Compression::CGzip => "C_GZIP",
            Compression::CXz => "C_XZ",
            Compression::CZstd => "C_ZSTD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "C_NONE" => Some(Self::CNone),
            "C_GZIP" => Some(Self::CGzip),
            "C_XZ" => Some(Self::CXz),
            "C_ZSTD" => Some(Self::CZstd),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Encryption {
    ENone = 0,
    EAes = 1,
}
impl Encryption {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Encryption::ENone => "E_NONE",
            Encryption::EAes => "E_AES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "E_NONE" => Some(Self::ENone),
            "E_AES" => Some(Self::EAes),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileKind {
    FkWal = 0,
    FkStore = 1,
}
impl FileKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FileKind::FkWal => "FK_WAL",
            FileKind::FkStore => "FK_STORE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FK_WAL" => Some(Self::FkWal),
            "FK_STORE" => Some(Self::FkStore),
            _ => None,
        }
    }
}
