// This file is @generated by prost-build.
/// A store file as its own header and signature block describe it.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<super::Id>,
    /// Holds ids first_id .. first_id + num_entries - 1.
    #[prost(message, optional, tag = "2")]
    pub first_id: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "3")]
    pub num_entries: u64,
    #[prost(uint64, tag = "4")]
    pub file_bytes: u64,
    /// WAL bytes before compression; 0 when not known.
    #[prost(uint64, tag = "5")]
    pub raw_bytes: u64,
    #[prost(enumeration = "Compression", tag = "6")]
    pub compression: i32,
    #[prost(enumeration = "Encryption", tag = "7")]
    pub encryption: i32,
    /// The same 64 bytes as in the file, so an object can be matched against
    /// this record without downloading it.
    #[prost(bytes = "bytes", tag = "8")]
    pub content_signature: ::prost::bytes::Bytes,
}
/// One record of `<instance>/normfs/system`. Only NormFS writes there; a
/// client write to that path is refused.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag = "1")]
    pub stamp: ::core::option::Option<super::Stamp>,
    #[prost(enumeration = "EventType", tag = "2")]
    pub r#type: i32,
    /// Emission never waits, so events dropped since the previous record are
    /// counted instead.
    #[prost(uint64, tag = "3")]
    pub dropped_before: u64,
    #[prost(string, tag = "4")]
    pub queue: ::prost::alloc::string::String,
    /// ET_FILE_STORED, ET_FILE_LANDED
    #[prost(message, optional, tag = "10")]
    pub file: ::core::option::Option<File>,
    /// ET_FILE_LANDED. Nothing is left to upload up to landed_through, so local
    /// copies up to it may be deleted.
    #[prost(string, tag = "20")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint64, tag = "21")]
    pub duration_ms: u64,
    #[prost(message, optional, tag = "22")]
    pub landed_through: ::core::option::Option<super::Id>,
    /// ET_UPLOAD_FAILED. Retried every second; attempts 1, 2, 4, 8 and so on
    /// are reported.
    #[prost(message, optional, tag = "30")]
    pub failed_file_id: ::core::option::Option<super::Id>,
    #[prost(enumeration = "UploadFailure", tag = "31")]
    pub upload_failure: i32,
    #[prost(uint32, tag = "32")]
    pub http_status: u32,
    #[prost(uint64, tag = "33")]
    pub local_bytes: u64,
    #[prost(uint64, tag = "34")]
    pub remote_bytes: u64,
    #[prost(string, tag = "35")]
    pub error: ::prost::alloc::string::String,
    /// ET_FILE_EVICTED
    #[prost(enumeration = "FileKind", tag = "40")]
    pub evicted_kind: i32,
    #[prost(message, optional, tag = "41")]
    pub evicted_file_id: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "42")]
    pub evicted_bytes: u64,
    #[prost(bool, tag = "43")]
    pub in_cloud: bool,
    /// ET_FILE_EVICTED, ET_EVICTION_BLOCKED
    #[prost(uint64, tag = "50")]
    pub queue_bytes: u64,
    /// ET_EVICTION_BLOCKED. Reported once per reason until the queue is back
    /// under the limit or the reason changes.
    #[prost(enumeration = "EvictionBlock", tag = "60")]
    pub eviction_block: i32,
    #[prost(message, optional, tag = "61")]
    pub held_at: ::core::option::Option<super::Id>,
    #[prost(uint64, tag = "62")]
    pub limit_bytes: u64,
    /// ET_POOL_STALLED: when the stall starts, every 30 seconds while it lasts,
    /// and once with resumed when it ends.
    #[prost(uint64, tag = "70")]
    pub waits: u64,
    #[prost(uint64, tag = "71")]
    pub stalled_for_ms: u64,
    #[prost(bool, tag = "72")]
    pub resumed: bool,
    /// ET_QUEUE_STARTED, ET_QUEUE_CLOSED
    #[prost(message, optional, tag = "80")]
    pub last_id: ::core::option::Option<super::Id>,
    #[prost(bool, tag = "81")]
    pub readonly: bool,
    #[prost(bool, tag = "82")]
    pub wal: bool,
    #[prost(bool, tag = "83")]
    pub store: bool,
    #[prost(bool, tag = "84")]
    pub cloud: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    EtFileStored = 0,
    EtFileLanded = 1,
    EtUploadFailed = 2,
    EtFileEvicted = 3,
    EtEvictionBlocked = 4,
    EtPoolStalled = 5,
    EtQueueStarted = 6,
    EtQueueClosed = 7,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EventType::EtFileStored => "ET_FILE_STORED",
            EventType::EtFileLanded => "ET_FILE_LANDED",
            EventType::EtUploadFailed => "ET_UPLOAD_FAILED",
            EventType::EtFileEvicted => "ET_FILE_EVICTED",
            EventType::EtEvictionBlocked => "ET_EVICTION_BLOCKED",
            EventType::EtPoolStalled => "ET_POOL_STALLED",
            EventType::EtQueueStarted => "ET_QUEUE_STARTED",
            EventType::EtQueueClosed => "ET_QUEUE_CLOSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ET_FILE_STORED" => Some(Self::EtFileStored),
            "ET_FILE_LANDED" => Some(Self::EtFileLanded),
            "ET_UPLOAD_FAILED" => Some(Self::EtUploadFailed),
            "ET_FILE_EVICTED" => Some(Self::EtFileEvicted),
            "ET_EVICTION_BLOCKED" => Some(Self::EtEvictionBlocked),
            "ET_POOL_STALLED" => Some(Self::EtPoolStalled),
            "ET_QUEUE_STARTED" => Some(Self::EtQueueStarted),
            "ET_QUEUE_CLOSED" => Some(Self::EtQueueClosed),
            _ => None,
        }
    }
}
/// Values as in the store header.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Compression {
    CNone = 0,
    CGzip = 1,
    CXz = 2,
    CZstd = 3,
}
impl Compression {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Compression::CNone => "C_NONE",
            Compression::CGzip => "C_GZIP",
            Compression::CXz => "C_XZ",
            Compression::CZstd => "C_ZSTD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "C_NONE" => Some(Self::CNone),
            "C_GZIP" => Some(Self::CGzip),
            "C_XZ" => Some(Self::CXz),
            "C_ZSTD" => Some(Self::CZstd),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Encryption {
    ENone = 0,
    EAes = 1,
}
impl Encryption {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Encryption::ENone => "E_NONE",
            Encryption::EAes => "E_AES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "E_NONE" => Some(Self::ENone),
            "E_AES" => Some(Self::EAes),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileKind {
    FkWal = 0,
    FkStore = 1,
}
impl FileKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FileKind::FkWal => "FK_WAL",
            FileKind::FkStore => "FK_STORE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FK_WAL" => Some(Self::FkWal),
            "FK_STORE" => Some(Self::FkStore),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UploadFailure {
    UfNetwork = 0,
    UfHttpStatus = 1,
    UfMissing = 2,
    UfSizeMismatch = 3,
    UfLocalRead = 4,
}
impl UploadFailure {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            UploadFailure::UfNetwork => "UF_NETWORK",
            UploadFailure::UfHttpStatus => "UF_HTTP_STATUS",
            UploadFailure::UfMissing => "UF_MISSING",
            UploadFailure::UfSizeMismatch => "UF_SIZE_MISMATCH",
            UploadFailure::UfLocalRead => "UF_LOCAL_READ",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UF_NETWORK" => Some(Self::UfNetwork),
            "UF_HTTP_STATUS" => Some(Self::UfHttpStatus),
            "UF_MISSING" => Some(Self::UfMissing),
            "UF_SIZE_MISMATCH" => Some(Self::UfSizeMismatch),
            "UF_LOCAL_READ" => Some(Self::UfLocalRead),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EvictionBlock {
    EbNotOffloaded = 0,
    EbDeleteFailed = 1,
    EbNothingFound = 2,
}
impl EvictionBlock {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EvictionBlock::EbNotOffloaded => "EB_NOT_OFFLOADED",
            EvictionBlock::EbDeleteFailed => "EB_DELETE_FAILED",
            EvictionBlock::EbNothingFound => "EB_NOTHING_FOUND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EB_NOT_OFFLOADED" => Some(Self::EbNotOffloaded),
            "EB_DELETE_FAILED" => Some(Self::EbDeleteFailed),
            "EB_NOTHING_FOUND" => Some(Self::EbNothingFound),
            _ => None,
        }
    }
}
